const U=window.BowUtils,S=window.BowStore;
const state={q:"",category:"",status:"",showSold:false,adultVerified:localStorage.getItem("bow_adult_verified")==="yes",pendingAdultCategory:"",sort:"nameAsc",maxPrice:"",onlyImages:false,view:"grid"};
const els={};document.addEventListener("DOMContentLoaded",init);
async function init(){cacheEls();applyConfig();bindEvents();try{await S.fetchItems();document.getElementById("sheetStatus").textContent="Listings are live";document.getElementById("loading").hidden=true;hydrateFilters();renderStats();renderDeals();renderProducts();}catch(e){document.getElementById("loading").textContent="Could not load current listings. Please try again later.";document.getElementById("sheetStatus").textContent="Listings unavailable";console.error(e);}}
function cacheEls(){["globalSearch","searchBtn","categoryFilter","categorySearchSelect","statusFilter","sortSelect","maxPriceFilter","onlyImagesFilter","showSoldFilter","adultModal","adultConfirmBtn","adultCancelBtn","clearFilters","productGrid","emptyState","gridViewBtn","listViewBtn","mobileMenuBtn","navBar"].forEach(id=>els[id]=document.getElementById(id));}
function applyConfig(){document.getElementById("storeName").textContent=STORE_CONFIG.storeName;document.getElementById("storeSubtitle").textContent=STORE_CONFIG.storeSubtitle;}
function bindEvents(){els.searchBtn.onclick=()=>{state.q=els.globalSearch.value.trim().toLowerCase();renderProducts();};els.globalSearch.oninput=()=>{state.q=els.globalSearch.value.trim().toLowerCase();renderProducts();};els.categorySearchSelect.onchange=e=>requestCategoryChange(e.target.value);els.categoryFilter.onchange=e=>requestCategoryChange(e.target.value);els.statusFilter.onchange=e=>{state.status=e.target.value;renderProducts();};els.showSoldFilter.onchange=e=>{state.showSold=e.target.checked;renderProducts();};els.sortSelect.onchange=e=>{state.sort=e.target.value;renderProducts();};els.maxPriceFilter.oninput=e=>{state.maxPrice=e.target.value;renderProducts();};els.onlyImagesFilter.onchange=e=>{state.onlyImages=e.target.checked;renderProducts();};els.clearFilters.onclick=()=>{Object.assign(state,{q:"",category:"",status:"",showSold:false,sort:"nameAsc",maxPrice:"",onlyImages:false});els.globalSearch.value="";els.categoryFilter.value="";els.categorySearchSelect.value="";els.statusFilter.value="";els.showSoldFilter.checked=false;els.sortSelect.value="nameAsc";els.maxPriceFilter.value="";els.onlyImagesFilter.checked=false;renderProducts();};els.mobileMenuBtn.onclick=()=>els.navBar.classList.toggle("open");els.adultConfirmBtn.onclick=confirmAdultCategory;els.adultCancelBtn.onclick=cancelAdultCategory;document.body.addEventListener("click",handleClicks);els.gridViewBtn.onclick=()=>setView("grid");els.listViewBtn.onclick=()=>setView("list");}
function hydrateFilters(){[...new Set(S.items.map(x=>x.category).filter(Boolean))].sort().forEach(cat=>{els.categoryFilter.add(new Option(cat,cat));els.categorySearchSelect.add(new Option(cat,cat));});}
function isAdultCategory(c){return String(c||"").trim().toLowerCase()==="adult";}
function isSold(item){return String(item?.availableStatus ?? item?.raw?.["Available"] ?? "").trim().toLowerCase()==="sold";}
function requestCategoryChange(category){if(isAdultCategory(category)&&!state.adultVerified){state.pendingAdultCategory=category;els.adultModal.hidden=false;els.categoryFilter.value=state.category||"";els.categorySearchSelect.value=state.category||"";return;}state.category=category;els.categoryFilter.value=category;els.categorySearchSelect.value=category;renderProducts();}
function confirmAdultCategory(){state.adultVerified=true;localStorage.setItem("bow_adult_verified","yes");els.adultModal.hidden=true;const c=state.pendingAdultCategory||"Adult";state.pendingAdultCategory="";state.category=c;els.categoryFilter.value=c;els.categorySearchSelect.value=c;renderProducts();}
function cancelAdultCategory(){state.pendingAdultCategory="";els.adultModal.hidden=true;els.categoryFilter.value=state.category||"";els.categorySearchSelect.value=state.category||"";}
function renderStats(){const soldCount=S.items.filter(x=>isSold(x)).length;const availableCount=S.items.length-soldCount;document.getElementById("statTotal").textContent=S.items.length;document.getElementById("statAvailable").textContent=availableCount;document.getElementById("statDeals").textContent=S.items.filter(x=>x.discount&&!isSold(x)).length;}
function filteredItems(){let items=[...S.items];if(!state.showSold)items=items.filter(x=>!isSold(x));if(!state.adultVerified||!isAdultCategory(state.category))items=items.filter(x=>!isAdultCategory(x.category));if(state.q)items=items.filter(x=>x.searchText.includes(state.q));if(state.category)items=items.filter(x=>x.category===state.category);if(state.maxPrice)items=items.filter(x=>x.salePrice<=Number(state.maxPrice));if(state.onlyImages)items=items.filter(x=>x.images.length);if(state.status==="ebay")items=items.filter(x=>x.onEbay);if(state.status==="discount")items=items.filter(x=>x.discount);items.sort((a,b)=>{if(state.sort==="priceLow")return a.salePrice-b.salePrice;if(state.sort==="priceHigh")return b.salePrice-a.salePrice;if(state.sort==="newest")return String(b.dateAdded).localeCompare(String(a.dateAdded));if(state.sort==="updated")return String(b.lastUpdated).localeCompare(String(a.lastUpdated));return a.name.localeCompare(b.name);});return items;}
function renderDeals(){const deals=S.items.filter(x=>(x.discount||x.salePrice<x.itemValue)&&!isSold(x)).slice(0,10);document.getElementById("dealRail").innerHTML=deals.length?deals.map(i=>`<a class="deal-card" href="pages/item.html?id=${encodeURIComponent(i.id)}"><img src="${U.escape(i.images[0]||STORE_CONFIG.defaultImage)}"><span>${U.escape(i.name)}</span><strong>${U.priceText(i.salePriceRaw)}</strong></a>`).join(""):"<p>No deals found yet.</p>";}
function renderProducts(){const items=filteredItems();els.productGrid.className=state.view==="list"?"product-grid list":"product-grid";els.emptyState.hidden=items.length>0;els.productGrid.innerHTML=items.map(cardHtml).join("");}
function cardHtml(i){const sold=isSold(i),img=i.images[0]||STORE_CONFIG.defaultImage,url=`pages/item.html?id=${encodeURIComponent(i.id)}`,wish=S.wishlist.includes(i.id)?"♥":"♡";return `<article class="product-card ${sold?"sold-card":""}"><button class="wish-btn" data-wish="${U.escape(i.id)}">${wish}</button><a class="image-btn" href="${url}"><img src="${U.escape(img)}" alt="${U.escape(i.name)}" onerror="this.src='${STORE_CONFIG.defaultImage}'"></a><div class="product-info"><p class="category">${U.escape(i.category)}</p><h3><a href="${url}">${U.escape(i.name)}</a></h3><p class="desc">${U.escape(i.description)}</p><div class="price-row"><strong>${U.priceText(i.salePriceRaw)}</strong>${i.discount?`<span class="discount">${U.escape(i.discount)}</span>`:""}</div><div class="meta">${i.internalCode?`<span>IC: ${U.escape(i.internalCode)}</span>`:""}${i.az?`<span>AZ: ${U.escape(i.az)}</span>`:""}<span class="${sold?"bad":"ok"}">${sold?"Sold":U.escape(i.availableStatus||"Available")}</span></div><div class="product-actions">${sold&&i.amazonLink?`<a class="button-link" target="_blank" href="${U.escape(i.amazonLink)}">Buy on Amazon</a>`:`<button data-cart="${U.escape(i.id)}">Add to cart</button>`}<a class="button-link secondary-action" href="${url}">Item Page</a></div></div></article>`;}
function handleClicks(e){const cart=e.target.closest("[data-cart]")?.dataset.cart,wish=e.target.closest("[data-wish]")?.dataset.wish;if(cart){S.addToCart(cart);U.toast("Added to cart");}if(wish){S.toggleWishlist(wish);renderProducts();U.toast("Wishlist updated");}}
function setView(v){state.view=v;els.gridViewBtn.classList.toggle("active",v==="grid");els.listViewBtn.classList.toggle("active",v==="list");renderProducts();}
