let filter={q:"",set:"",color:"",sort:"name"};
document.addEventListener("DOMContentLoaded",async()=>{await MTG.init();hydrate();bind();render();});
function hydrate(){setFilter.innerHTML='<option value="">All Sets</option>';MTG.sets.forEach(s=>setFilter.add(new Option(s.name,s.code)));colorFilter.innerHTML='<option value="">All Colors</option>';["W","U","B","R","G","C"].forEach(c=>colorFilter.add(new Option(colorName(c),c)));}
function bind(){search.oninput=()=>{filter.q=search.value.toLowerCase();render();};setFilter.onchange=()=>{filter.set=setFilter.value;render();};colorFilter.onchange=()=>{filter.color=colorFilter.value;render();};sortFilter.onchange=()=>{filter.sort=sortFilter.value;render();};}
function wanted(){let cards=MTG.cards.filter(c=>getEntry(c.id).want);if(filter.q)cards=cards.filter(c=>c.search.includes(filter.q));if(filter.set)cards=cards.filter(c=>c.set===filter.set);if(filter.color){if(filter.color==="C")cards=cards.filter(c=>!c.colors?.length);else cards=cards.filter(c=>c.colors?.includes(filter.color));}cards.sort((a,b)=>filter.sort==="set"?(a.set_name+a.collector_number).localeCompare(b.set_name+b.collector_number):a.name.localeCompare(b.name));return cards;}
function render(){const cards=wanted();const owned=cards.filter(c=>Number(getEntry(c.id).owned||0)>0);totalCards.textContent=cards.length;ownedCards.textContent=owned.length;missingCards.textContent=cards.length-owned.length;totalValue.textContent=Util.money(collectionValue(cards));status.textContent="Want list loaded";grid.innerHTML=cards.map(c=>{const e=getEntry(c.id);return `<article class="card"><img class="card-img" src="${Util.escape(c.image)}" onerror="this.src='../${APP_CONFIG.defaultImage}'"><div class="card-body"><div class="meta"><span class="badge wish">Want</span>${Number(e.owned||0)>0?`<span class="badge owned">Owned ${e.owned}</span>`:""}</div><h3>${Util.escape(c.name)}</h3><p>${Util.escape(c.set_name)} • #${Util.escape(c.collector_number)}</p><p>${Util.escape(c.rarity)} • ${Util.escape(c.type_line)}</p><div class="actions"><button class="secondary" onclick="removeWant('${c.id}')">Remove Want</button>${cardInfoUrl(c)?`<a class="secondary" target="_blank" rel="noopener" href="${Util.escape(cardInfoUrl(c))}">Card Info / Prices</a>`:""}</div></div></article>`}).join("")||"<section class='empty'>No wanted cards yet.</section>";}
async function removeWant(id){const e=getEntry(id);e.want=false;await saveEntry(id);render();}


function cardInfoUrl(c){
  return c.scryfall_uri || (c.scryfallId ? "https://scryfall.com/card/" + c.scryfallId : "");
}
