let filter={q:"",year:"",download:"",sort:"date"};
document.addEventListener("DOMContentLoaded",async()=>{await LORCANA.init();hydrate();bind();updateStats();render();status.textContent=LORCANA.sets.length?"Saved sets loaded.":"Pull sets to begin.";});
function bind(){pullSetsBtn.onclick=async()=>{try{status.textContent="Pulling sets...";await LORCANA.pullSets(msg=>status.textContent=msg);await LORCANA.loadSaved();hydrate();updateStats();render();status.textContent="Sets loaded.";}catch(e){console.error(e);status.textContent=e.message||"Could not pull sets.";}};loadAllBtn.onclick=async()=>{if(!confirm("Load every Lorcana set?"))return;try{loadPanel.hidden=false;await loadAllSets((msg,done,total)=>{status.textContent=msg;loadStatus.textContent=total?`${msg} (${done}/${total})`:msg;if(total)loadBar.style.width=Math.max(5,Math.round(done/total*100))+"%";});await LORCANA.loadSaved();hydrate();updateStats();render();loadStatus.textContent="Done loading all sets.";loadBar.style.width="100%";Util.toast("All sets loaded");setTimeout(()=>loadPanel.hidden=true,3000);}catch(e){console.error(e);status.textContent=e.message||"Could not load all sets.";}};setSearch.oninput=()=>{filter.q=setSearch.value.toLowerCase();render();};yearFilter.onchange=()=>{filter.year=yearFilter.value;render();};downloadFilter.onchange=()=>{filter.download=downloadFilter.value;render();};sortFilter.onchange=()=>{filter.sort=sortFilter.value;render();};}
function hydrate(){yearFilter.innerHTML='<option value="">All Years</option>';[...new Set(LORCANA.sets.map(s=>s.year).filter(Boolean))].sort((a,b)=>b.localeCompare(a)).forEach(y=>yearFilter.add(new Option(y,y)));}
function rows(){let s=[...LORCANA.sets];if(filter.q)s=s.filter(x=>(x.name+" "+x.code).toLowerCase().includes(filter.q));if(filter.year)s=s.filter(x=>x.year===filter.year);if(filter.download==="downloaded")s=s.filter(x=>LORCANA.cardsForSet(x.code).length);if(filter.download==="not")s=s.filter(x=>!LORCANA.cardsForSet(x.code).length);s.sort((a,b)=>{if(filter.sort==="name")return a.name.localeCompare(b.name);if(filter.sort==="owned")return ownedCount(LORCANA.cardsForSet(b.code))-ownedCount(LORCANA.cardsForSet(a.code));return String(b.released_at).localeCompare(String(a.released_at));});return s;}
function render(){const data=rows();setGrid.innerHTML=data.map(setCardHTML).join("")||"<section class='empty'>No sets found.</section>";}
function setCardHTML(s){const cards=LORCANA.cardsForSet(s.code), owned=ownedCount(cards), pct=cards.length?Math.round(owned/cards.length*100):0, cover=s.coverImage||cards[0]?.image||"";return `<article class="set-card"><div class="set-card-cover">${cover?`<img src="${Util.escape(cover)}">`:`<div class="rune">✦</div>`}</div><div class="set-card-body"><p class="eyebrow">${Util.escape(String(s.code).toUpperCase())} ${s.year?`• ${Util.escape(s.year)}`:""}</p><h3>${Util.escape(s.name)}</h3><p>${cards.length?`${owned} / ${cards.length} owned • ${pct}%`:`${s.card_count||"?"} cards listed`}</p><div class="bar"><div style="width:${pct}%"></div></div><div class="actions" style="margin-top:12px"><button class="primary" onclick="openSet('${Util.escape(s.code)}')">${cards.length?"Open Set":"Load Cards"}</button>${cards.length?`<button class="secondary" onclick="redownloadSet('${Util.escape(s.code)}')">Redownload</button>`:""}</div></div></article>`;}
async function openSet(code){if(LORCANA.cardsForSet(code).length){location.href="set.html?set="+encodeURIComponent(code);return;}await redownloadSet(code,true);}
async function redownloadSet(code,go=false){try{status.textContent="Loading set cards...";await LORCANA.loadSetCards(code,msg=>status.textContent=msg);await LORCANA.loadSaved();hydrate();updateStats();render();if(go)location.href="set.html?set="+encodeURIComponent(code);else Util.toast("Set downloaded");}catch(e){console.error(e);status.textContent=e.message||"Could not load set.";}}
