document.addEventListener("DOMContentLoaded",async()=>{await LORCANA.init();refresh();exportBtn.onclick=exportBackup;importFile.onchange=importBackup;removeNotOwnedBtn.onclick=removeNotOwned;clearCardsBtn.onclick=clearCards;clearCollectionBtn.onclick=clearCollection;clearAllBtn.onclick=clearAll;});
async function refresh(){cardStat.textContent=LORCANA.cards.length;setStat.textContent=LORCANA.sets.length;entryStat.textContent=Object.values(LORCANA.collection).filter(e=>Number(e.owned||0)>0||Number(e.foil||0)>0||e.want||e.notes).length;valueStat.textContent=Util.money(collectionValue(collectionCards()));}
async function exportBackup(){const entries=await DB.all(APP_CONFIG.collectionStore);download("lorcana-collector-backup.json",JSON.stringify({app:APP_CONFIG.appName,version:APP_CONFIG.appVersion,exportedAt:new Date().toISOString(),collection:entries,cards:LORCANA.cards,sets:LORCANA.sets},null,2),"application/json");}
async function importBackup(e){const file=e.target.files[0];if(!file)return;const data=JSON.parse(await file.text());if(data.cards)await DB.bulkPut(APP_CONFIG.cardsStore,data.cards,200);if(data.sets)await DB.bulkPut(APP_CONFIG.setsStore,data.sets,100);if(data.collection)await DB.bulkPut(APP_CONFIG.collectionStore,Array.isArray(data.collection)?data.collection:Object.values(data.collection),200);await LORCANA.loadSaved();refresh();Util.toast("Backup imported");}
async function removeNotOwned(){if(!confirm("Remove not-owned cards but keep owned and wanted cards?"))return;const keep=LORCANA.cards.filter(c=>Number(getEntry(c.id).owned||0)>0||Number(getEntry(c.id).foil||0)>0||getEntry(c.id).want);const affected=new Set(LORCANA.cards.filter(c=>!keep.includes(c)).map(c=>c.setCode));await DB.clear(APP_CONFIG.cardsStore);if(keep.length)await DB.bulkPut(APP_CONFIG.cardsStore,keep,200);for(const code of affected)await LORCANA.markSetTrimmed(code);await LORCANA.loadSaved();refresh();Util.toast("Removed not-owned cards");}
async function clearCards(){if(!confirm("Clear downloaded cards and sets? Collection entries stay."))return;await DB.clear(APP_CONFIG.cardsStore);await DB.clear(APP_CONFIG.setsStore);await LORCANA.loadSaved();refresh();}
async function clearCollection(){if(!confirm("Clear collection entries?"))return;await DB.clear(APP_CONFIG.collectionStore);await LORCANA.loadSaved();refresh();}
async function clearAll(){if(!confirm("Clear everything?"))return;await DB.clear(APP_CONFIG.cardsStore);await DB.clear(APP_CONFIG.setsStore);await DB.clear(APP_CONFIG.collectionStore);await DB.clear(APP_CONFIG.metaStore);await LORCANA.loadSaved();refresh();}
function download(name,content,type){const blob=new Blob([content],{type});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();}
